"""refresh tokens, login attempts, agent actions (+ RLS for agent_actions)

Revision ID: 20261002_03
Revises: 20261002_02
Create Date: 2026-10-02 03:36:14.164034
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20261002_03'
down_revision: Union[str, None] = '20261002_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email_hash'), 'login_attempts', ['email_hash'], unique=False)
    op.create_table('agent_actions',
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected', 'executed', 'failed', 'expired')", name='ck_agent_actions_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_status'), 'agent_actions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_actions_tenant_id'), 'agent_actions', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # agent_actions is tenant-owned: same fail-closed isolation as the baseline tables (migration 02).
    op.execute("ALTER TABLE agent_actions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE agent_actions FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON agent_actions
          USING (tenant_id = app_tenant_id())
          WITH CHECK (tenant_id = app_tenant_id())
        """
    )
    # refresh_tokens and login_attempts are global auth bookkeeping read before a tenant is known; they are
    # still closed to the Supabase Data API roles by the lockdown below.
    op.execute(
        """
        DO $$
        DECLARE r text;
        BEGIN
          FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
              EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
            END IF;
          END LOOP;
        END $$
        """
    )



def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON agent_actions")
    op.execute("ALTER TABLE agent_actions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE agent_actions DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_agent_actions_tenant_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_status'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_login_attempts_email_hash'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
