"""soft delete, versions, numeric money

Revision ID: 20261002_04
Revises: 20261002_03
Create Date: 2026-10-02 04:18:11.003085
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20261002_04'
down_revision: Union[str, None] = '20261002_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_customers_tenant_phone'), 'customers', type_='unique')
    op.create_index('uq_customers_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.add_column('inventory_items', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('inventory_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # text -> numeric needs an explicit cast. Rule: the FIRST number in the text ('2500 PKR' -> 2500.00,
    # '2000-3000 PKR' -> 2000.00, '1,299.50' -> 1299.50); text with no number becomes NULL.
    op.alter_column('inventory_items', 'price',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True,
               postgresql_using="CASE WHEN price ~ '[0-9]' AND length(replace(substring(price from '[0-9][0-9,]*(?:[.][0-9]+)?'), ',', '')) <= 12 THEN replace(substring(price from '[0-9][0-9,]*(?:[.][0-9]+)?'), ',', '')::numeric(14,2) END")
    op.drop_constraint(op.f('uq_inventory_items_tenant_sku'), 'inventory_items', type_='unique')
    op.create_index('uq_inventory_items_tenant_sku', 'inventory_items', ['tenant_id', 'sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('orders', 'budget',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True,
               postgresql_using="CASE WHEN budget ~ '[0-9]' AND length(replace(substring(budget from '[0-9][0-9,]*(?:[.][0-9]+)?'), ',', '')) <= 12 THEN replace(substring(budget from '[0-9][0-9,]*(?:[.][0-9]+)?'), ',', '')::numeric(14,2) END")
    op.add_column('vendors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'deleted_at')
    op.alter_column('orders', 'budget',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('orders', 'version')
    op.drop_index('uq_inventory_items_tenant_sku', table_name='inventory_items', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # soft-deleted rows could collide with live ones once uniqueness covers every row again: keep them,
    # but make their sku unique (lossy by design: the original sku text is replaced)
    op.execute("UPDATE inventory_items SET sku = left(coalesce(sku, ''), 50) || '#deleted-' || id::text WHERE deleted_at IS NOT NULL")
    op.create_unique_constraint(op.f('uq_inventory_items_tenant_sku'), 'inventory_items', ['tenant_id', 'sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('inventory_items', 'price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('inventory_items', 'deleted_at')
    op.drop_column('inventory_items', 'version')
    op.drop_index('uq_customers_tenant_phone', table_name='customers', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.execute("UPDATE customers SET phone = 'del-' || left(replace(id::text, '-', ''), 24) WHERE deleted_at IS NOT NULL")
    op.create_unique_constraint(op.f('uq_customers_tenant_phone'), 'customers', ['tenant_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'deleted_at')
    # ### end Alembic commands ###
