"""initial

Revision ID: e2cd7dc01bac
Revises: 
Create Date: 2026-08-24 19:25:08.136180
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e2cd7dc01bac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('issue_summary', sa.String(length=500), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'vendor', 'staff', 'customer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('waba_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_user_id'), 'vendors', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_vendor_id'), 'customers', ['vendor_id'], unique=False)
    op.create_table('facebook_accounts',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    op.create_index(op.f('ix_facebook_accounts_vendor_id'), 'facebook_accounts', ['vendor_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('incoming_units', sa.Integer(), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_vendor_id'), 'inventory_items', ['vendor_id'], unique=False)
    op.create_table('marketing_posts',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('fb_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_posts_vendor_id'), 'marketing_posts', ['vendor_id'], unique=False)
    op.create_table('scheduled_campaigns',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_campaigns_vendor_id'), 'scheduled_campaigns', ['vendor_id'], unique=False)
    op.create_table('messages',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='messagedirection'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('wa_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_vendor_id'), 'messages', ['vendor_id'], unique=False)
    op.create_table('orders',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_vendor_id'), 'orders', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_vendor_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_messages_vendor_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_scheduled_campaigns_vendor_id'), table_name='scheduled_campaigns')
    op.drop_table('scheduled_campaigns')
    op.drop_index(op.f('ix_marketing_posts_vendor_id'), table_name='marketing_posts')
    op.drop_table('marketing_posts')
    op.drop_index(op.f('ix_inventory_items_vendor_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_facebook_accounts_vendor_id'), table_name='facebook_accounts')
    op.drop_table('facebook_accounts')
    op.drop_index(op.f('ix_customers_vendor_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_vendors_user_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
