/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent-runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_agent_runs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-runs/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Status */
        get: operations["agent_status_api_v1_agent_runs_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-runs/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Agent Switch
         * @description The owner's kill switch: takes effect on the very next message, no deploy.
         */
        put: operations["set_agent_switch_api_v1_agent_runs_switch_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_agent_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_api_v1_approvals__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_api_v1_approvals__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_approvals__action_id__patch"];
        trace?: never;
    };
    "/api/v1/approvals/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve and run exactly what was proposed. If the rules now refuse it, it is marked failed and nothing changes.
         */
        post: operations["approve_api_v1_approvals__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{action_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_approvals__action_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, pick the tenant, return tokens carrying ``tenant_id`` and ``role``.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session's refresh token. Idempotent: an unknown token is not an error.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate a refresh token and issue a new access token with the membership's *current* role.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create the user, the tenant and the owner membership in one transaction.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Tenant
         * @description Issue tokens for another tenant the caller belongs to.
         */
        post: operations["switch_tenant_api_v1_auth_switch_tenant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat With Sales Agent
         * @description One turn with the sales agent. Anything it wants to change comes back as an approval card, never as a change.
         */
        post: operations["chat_with_sales_agent_api_v1_chat_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_v1_customers__get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_v1_customers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_v1_customers__customer_id__get"];
        put?: never;
        post?: never;
        /** Delete Customer */
        delete: operations["delete_customer_api_v1_customers__customer_id__delete"];
        options?: never;
        head?: never;
        /** Update Customer */
        patch: operations["update_customer_api_v1_customers__customer_id__patch"];
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer Ledger */
        get: operations["customer_ledger_api_v1_customers__customer_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Payment */
        post: operations["record_payment_api_v1_customers__customer_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_inventory__get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_inventory__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_inventory__product_id__get"];
        put?: never;
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_v1_inventory__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_inventory__product_id__patch"];
        trace?: never;
    };
    "/api/v1/inventory/{product_id}/stock-movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stock Movements */
        get: operations["list_stock_movements_api_v1_inventory__product_id__stock_movements_get"];
        put?: never;
        /** Add Stock Movement */
        post: operations["add_stock_movement_api_v1_inventory__product_id__stock_movements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse Order
         * @description Undo a posted sale (PRD §13.2: reversing is a manager's decision). Stock, payments and udhaar are put back.
         */
        post: operations["reverse_order_api_v1_orders__order_id__reverse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Sale */
        post: operations["post_sale_api_v1_sales__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sales/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Sale
         * @description Add up a sale for the form (prices, totals, stock) without writing anything.
         */
        post: operations["preview_sale_api_v1_sales_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team */
        get: operations["list_team_api_v1_team__get"];
        put?: never;
        /** Add Team Member */
        post: operations["add_team_member_api_v1_team__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Team Member */
        delete: operations["remove_team_member_api_v1_team__membership_id__delete"];
        options?: never;
        head?: never;
        /** Change Team Member Role */
        patch: operations["change_team_member_role_api_v1_team__membership_id__patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, pick the tenant, return tokens carrying ``tenant_id`` and ``role``.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session's refresh token. Idempotent: an unknown token is not an error.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate a refresh token and issue a new access token with the membership's *current* role.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create the user, the tenant and the owner membership in one transaction.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/switch-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Tenant
         * @description Issue tokens for another tenant the caller belongs to.
         */
        post: operations["switch_tenant_auth_switch_tenant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vapi/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vapi Webhook
         * @description Handle function-call messages from VAPI.
         */
        post: operations["vapi_webhook_vapi_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Webhook
         * @description Meta's subscription handshake: echo ``hub.challenge`` as plain text (a JSON string would fail verification).
         */
        get: operations["verify_webhook_webhook_get"];
        put?: never;
        /** Inbound Webhook */
        post: operations["inbound_webhook_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Test Webhook
         * @description Simple endpoint to check that the webhook route is reachable.
         */
        get: operations["test_webhook_webhook_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunDetail */
        AgentRunDetail: {
            /** Action Ids */
            action_ids: string[];
            /** Agent */
            agent: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Text */
            input_text: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "failed" | "step_limit" | "paused" | "spend_limit";
            /** Output Text */
            output_text: string;
            /** Session Id */
            session_id: string;
            /** Spend Usd */
            spend_usd: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Trace */
            trace: {
                [key: string]: unknown;
            }[];
            /** User Id */
            user_id: string | null;
            /** User Name */
            user_name: string | null;
        };
        /** AgentRunOut */
        AgentRunOut: {
            /** Action Ids */
            action_ids: string[];
            /** Agent */
            agent: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Text */
            input_text: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "failed" | "step_limit" | "paused" | "spend_limit";
            /** Output Text */
            output_text: string;
            /** Session Id */
            session_id: string;
            /** Spend Usd */
            spend_usd: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** User Id */
            user_id: string | null;
            /** User Name */
            user_name: string | null;
        };
        /** AgentStatus */
        AgentStatus: {
            /** Enabled */
            enabled: boolean;
            /** Month Cap Usd */
            month_cap_usd: string;
            /** Month Spend Usd */
            month_spend_usd: string;
            /** Percent Used */
            percent_used: number;
            /** Runs This Month */
            runs_this_month: number;
        };
        /** AgentSwitch */
        AgentSwitch: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * ApprovalEdit
         * @description Replace the proposed payload (for example a smaller quantity). It is re-validated like a new request.
         */
        ApprovalEdit: {
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** ApprovalOut */
        ApprovalOut: {
            /** Agent */
            agent: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided By */
            decided_by: string | null;
            /** Decision Note */
            decision_note: string | null;
            /** Details */
            details: string[];
            /** Executed At */
            executed_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Requested By */
            requested_by: string | null;
            /** Requested By Name */
            requested_by_name: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "executed" | "failed" | "expired";
            /** Summary */
            summary: string;
            /** Tool */
            tool: string;
        };
        /** ApprovalReject */
        ApprovalReject: {
            /** Reason */
            reason: string;
        };
        /**
         * ChatAction
         * @description An approval the agent filed during this turn, shown as a card in the chat.
         */
        ChatAction: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "executed" | "failed" | "expired";
            /** Summary */
            summary: string;
            /** Tool */
            tool: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Actions */
            actions: components["schemas"]["ChatAction"][];
            /** Notice */
            notice?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "failed" | "step_limit" | "paused" | "spend_limit";
            /** Reply */
            reply: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Session Id */
            session_id: string;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Phone */
            phone: string;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Address */
            address: string | null;
            /** Balance */
            balance?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Phone */
            phone: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CustomerUpdate
         * @description Partial update; unknown fields (tenant_id, balance) are rejected.
         */
        CustomerUpdate: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LedgerEntryOut */
        LedgerEntryOut: {
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "debit" | "credit";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref Id */
            ref_id: string | null;
            /** Ref Type */
            ref_type: string | null;
        };
        /**
         * LoginRequest
         * @description PRD F-001. ``tenant_id`` is only needed when the user belongs to more than one tenant.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Tenant Id */
            tenant_id?: string | null;
        };
        /** MeOut */
        MeOut: {
            /** Memberships */
            memberships: components["schemas"]["TenantMembershipOut"][];
            role: components["schemas"]["TenantRole"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            user: components["schemas"]["UserOut"];
        };
        /** OrderDetail */
        OrderDetail: {
            /** Amount Due */
            amount_due: string;
            /** Amount Paid */
            amount_paid: string;
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Discount */
            discount: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Count */
            item_count: number;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Note */
            note: string | null;
            /** Payments */
            payments: components["schemas"]["OrderPaymentOut"][];
            /** Status */
            status: string;
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrderItemOut */
        OrderItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line Total */
            line_total: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost: string | null;
            /** Unit Price */
            unit_price: string;
        };
        /** OrderPaymentOut */
        OrderPaymentOut: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Method */
            method: string;
            /** Status */
            status: string;
        };
        /** OrderSummary */
        OrderSummary: {
            /** Amount Due */
            amount_due: string;
            /** Amount Paid */
            amount_paid: string;
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Discount */
            discount: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Count */
            item_count: number;
            /** Status */
            status: string;
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
        };
        /** Page[AgentRunOut] */
        Page_AgentRunOut_: {
            /** Items */
            items: components["schemas"]["AgentRunOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[ApprovalOut] */
        Page_ApprovalOut_: {
            /** Items */
            items: components["schemas"]["ApprovalOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[CustomerOut] */
        Page_CustomerOut_: {
            /** Items */
            items: components["schemas"]["CustomerOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[LedgerEntryOut] */
        Page_LedgerEntryOut_: {
            /** Items */
            items: components["schemas"]["LedgerEntryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[OrderSummary] */
        Page_OrderSummary_: {
            /** Items */
            items: components["schemas"]["OrderSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** Page[StockMovementOut] */
        Page_StockMovementOut_: {
            /** Items */
            items: components["schemas"]["StockMovementOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * PaymentCreate
         * @description A customer settling part or all of what they owe.
         */
        PaymentCreate: {
            /** Amount */
            amount: number | string;
            /**
             * Method
             * @enum {string}
             */
            method: "cash" | "card" | "bank" | "wallet";
        };
        /** PaymentOut */
        PaymentOut: {
            /** Amount */
            amount: string;
            /** Balance */
            balance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Method */
            method: string;
        };
        /** ProductCreate */
        ProductCreate: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Category */
            category?: string | null;
            /** Cost */
            cost?: number | string | null;
            /** Name */
            name: string;
            /** Price */
            price: number | string;
            /**
             * Qty On Hand
             * @default 0
             */
            qty_on_hand: number;
            /** Reorder Level */
            reorder_level?: number | null;
            /** Sku */
            sku: string;
            /** Vendor Id */
            vendor_id?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Active */
            active: boolean;
            /** Category */
            category: string | null;
            /** Cost */
            cost: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Low Stock */
            low_stock: boolean;
            /** Name */
            name: string;
            /** Price */
            price: string;
            /** Qty On Hand */
            qty_on_hand: number;
            /** Reorder Level */
            reorder_level: number;
            /** Sku */
            sku: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor Id */
            vendor_id: string | null;
        };
        /**
         * ProductUpdate
         * @description Partial update. Unknown fields are rejected, so ``qty_on_hand`` and ``tenant_id`` can never be smuggled in.
         */
        ProductUpdate: {
            /** Active */
            active?: boolean | null;
            /** Category */
            category?: string | null;
            /** Cost */
            cost?: number | string | null;
            /** Name */
            name?: string | null;
            /** Price */
            price?: number | string | null;
            /** Reorder Level */
            reorder_level?: number | null;
            /** Sku */
            sku?: string | null;
            /** Vendor Id */
            vendor_id?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description PRD F-002: create an account and its first shop in one step.
         */
        RegisterRequest: {
            /** Accept Terms */
            accept_terms: boolean;
            /** City */
            city?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** Phone */
            phone: string;
            /** Shop Name */
            shop_name: string;
        };
        /**
         * ReverseRequest
         * @description Why a posted sale is being undone (kept in the audit log and on the order).
         */
        ReverseRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * SaleCreate
         * @description PRD F-007 New sale. The channel is set by the source (here: the point of sale), never by the caller.
         */
        SaleCreate: {
            /** Amount Paid */
            amount_paid?: number | string | null;
            /** Customer Id */
            customer_id?: string | null;
            /**
             * Discount
             * @default 0.00
             */
            discount: number | string;
            /** Items */
            items: components["schemas"]["SaleLine"][];
            /** Note */
            note?: string | null;
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "cash" | "card" | "bank" | "wallet" | "udhaar";
            /**
             * Stock Override
             * @default false
             */
            stock_override: boolean;
        };
        /** SaleLine */
        SaleLine: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Qty */
            qty: number;
            /** Unit Price */
            unit_price?: number | string | null;
        };
        /** SalePreview */
        SalePreview: {
            /** Amount Due */
            amount_due: string;
            /** Amount Paid */
            amount_paid: string;
            /** Discount */
            discount: string;
            /** Lines */
            lines: components["schemas"]["SalePreviewLine"][];
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
            /** Warnings */
            warnings: string[];
        };
        /** SalePreviewLine */
        SalePreviewLine: {
            /** Available */
            available: number;
            /** Enough Stock */
            enough_stock: boolean;
            /** Line Total */
            line_total: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Unit Price */
            unit_price: string;
        };
        /**
         * SalePreviewRequest
         * @description What the New sale form asks the server to add up (the browser never does money arithmetic).
         */
        SalePreviewRequest: {
            /** Amount Paid */
            amount_paid?: number | string | null;
            /**
             * Discount
             * @default 0.00
             */
            discount: number | string;
            /** Items */
            items?: components["schemas"]["SaleLine"][];
            /** Payment Method */
            payment_method?: ("cash" | "card" | "bank" | "wallet" | "udhaar") | null;
        };
        /**
         * StockMovementCreate
         * @description A manual stock change. ``delta`` is signed: positive adds stock, negative removes it.
         */
        StockMovementCreate: {
            /** Delta */
            delta: number;
            /** Note */
            note?: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "purchase" | "adjustment" | "return";
        };
        /** StockMovementOut */
        StockMovementOut: {
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delta */
            delta: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Reason */
            reason: string;
            /** Ref Id */
            ref_id: string | null;
            /** Ref Type */
            ref_type: string | null;
        };
        /** SwitchTenantRequest */
        SwitchTenantRequest: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /**
         * TeamMemberCreate
         * @description Add a person to the shop. A new person needs an initial password to be given to them; someone who already has
         *     an account (for example in another shop) keeps theirs and ``password`` is ignored.
         */
        TeamMemberCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "manager" | "staff";
        };
        /** TeamMemberOut */
        TeamMemberOut: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is You */
            is_you: boolean;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /** Name */
            name: string | null;
            /**
             * New Account
             * @default false
             */
            new_account: boolean;
            /** Role */
            role: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * TeamMemberUpdate
         * @description Only the role can change; unknown fields are rejected.
         */
        TeamMemberUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "manager" | "staff";
        };
        /** TenantMembershipOut */
        TenantMembershipOut: {
            role: components["schemas"]["TenantRole"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /**
         * TenantRole
         * @description Roles a user can hold inside one tenant. ``platform_admin`` is a flag on ``users``.
         * @enum {string}
         */
        TenantRole: "owner" | "manager" | "staff";
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            role: components["schemas"]["TenantRole"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Platform Admin */
            is_platform_admin: boolean;
            /** Name */
            name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VapiFunctionCall */
        VapiFunctionCall: {
            /**
             * Arguments
             * @default {}
             */
            arguments: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
        };
        /** VapiMessage */
        VapiMessage: {
            functionCall?: components["schemas"]["VapiFunctionCall"] | null;
            /** Type */
            type: string;
        };
        /** VapiWebhookRequest */
        VapiWebhookRequest: {
            /** Call */
            call?: {
                [key: string]: unknown;
            } | null;
            message: components["schemas"]["VapiMessage"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_v1_agent_runs__get: {
        parameters: {
            query?: {
                outcome?: string | null;
                agent?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AgentRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_status_api_v1_agent_runs_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatus"];
                };
            };
        };
    };
    set_agent_switch_api_v1_agent_runs_switch_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSwitch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_agent_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_api_v1_approvals__get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApprovalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_api_v1_approvals__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_approvals__action_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_approvals__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_approvals__action_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalReject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_tenant_api_v1_auth_switch_tenant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_with_sales_agent_api_v1_chat_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_v1_customers__get: {
        parameters: {
            query?: {
                q?: string | null;
                owing_only?: boolean;
                sort?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CustomerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_customer_api_v1_customers__customer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_v1_customers__customer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer_ledger_api_v1_customers__customer_id__ledger_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LedgerEntryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_api_v1_customers__customer_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_inventory__get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                active?: boolean | null;
                low_stock?: boolean | null;
                sort?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_inventory__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_inventory__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_inventory__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_inventory__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stock_movements_api_v1_inventory__product_id__stock_movements_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StockMovementOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_stock_movement_api_v1_inventory__product_id__stock_movements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMovementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders__get: {
        parameters: {
            query?: {
                status?: string | null;
                channel?: string | null;
                customer_id?: string | null;
                q?: string | null;
                sort?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrderSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_order_api_v1_orders__order_id__reverse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sale_api_v1_sales__post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_sale_api_v1_sales_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_api_v1_team__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOut"][];
                };
            };
        };
    };
    add_team_member_api_v1_team__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_team_member_api_v1_team__membership_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_team_member_role_api_v1_team__membership_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_tenant_auth_switch_tenant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vapi_webhook_vapi_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vapi-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VapiWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_webhook_webhook_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    inbound_webhook_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    test_webhook_webhook_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
