"""Shared utility layer for BazaarFlow backend."""

from .repository import (
    configure_db_root,
    get_customer,
    get_vendor,
    get_vendor_by_phone_number_id,
    list_customers,
    list_messages,
    list_vendors,
    recent_messages,
    record_message,
    update_vendor_settings,
    upsert_customer,
    upsert_vendor,
)
from .marketing_repository import (
    configure_marketing_root,
    delete_facebook_account,
    get_facebook_account,
    get_schedule,
    list_facebook_accounts,
    list_marketing_posts,
    mark_schedule_triggered,
    record_marketing_post,
    save_schedule,
    delete_marketing_post,
    update_post_insights,
    upsert_facebook_account,
)


__all__ = [
    "configure_db_root",
    "configure_marketing_root",
    "delete_facebook_account",
    "get_customer",
    "get_facebook_account",
    "get_vendor",
    "get_vendor_by_phone_number_id",
    "get_schedule",
    "list_customers",
    "list_facebook_accounts",
    "list_messages",
    "list_marketing_posts",
    "list_vendors",
    "recent_messages",
    "record_message",
    "record_marketing_post",
    "delete_marketing_post",
    "update_vendor_settings",
    "update_post_insights",
    "upsert_customer",
    "upsert_facebook_account",
    "upsert_vendor",
    "mark_schedule_triggered",
    "save_schedule",
]
