"""Repositories package — re-exports from all sub-modules for backwards compatibility."""
from app.repositories import marketing_repository, marketing_scheduled_repository, user_repository
from app.repositories.marketing_repository import (
    delete_facebook_account,
    delete_marketing_post,
    get_comment_reply,
    get_facebook_account,
    get_schedule,
    list_facebook_accounts,
    list_marketing_posts,
    list_schedules,
    mark_schedule_triggered,
    record_comment_reply,
    record_marketing_post,
    save_schedule,
    update_post_insights,
    upsert_facebook_account,
)
from app.repositories.repository import (
    get_customer,
    get_vendor,
    get_vendor_by_phone_number_id,
    list_customers,
    list_messages,
    list_vendors,
    recent_messages,
    record_message,
    update_vendor_settings,
    upsert_customer,
    upsert_vendor,
)

__all__ = [
    "delete_facebook_account",
    "delete_marketing_post",
    "get_comment_reply",
    "get_customer",
    "get_facebook_account",
    "get_schedule",
    "get_vendor",
    "get_vendor_by_phone_number_id",
    "list_customers",
    "list_facebook_accounts",
    "list_marketing_posts",
    "list_messages",
    "list_schedules",
    "list_vendors",
    "mark_schedule_triggered",
    "recent_messages",
    "record_comment_reply",
    "record_marketing_post",
    "record_message",
    "save_schedule",
    "update_post_insights",
    "update_vendor_settings",
    "upsert_customer",
    "upsert_facebook_account",
    "upsert_vendor",
    "marketing_repository",
    "marketing_scheduled_repository",
    "user_repository",
]
